"""重新同步init.sql最新表结构

Revision ID: b6998d1c9912
Revises: 1fc756a06ab7
Create Date: 2026-06-30 15:38:01.658883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6998d1c9912'
down_revision: Union[str, Sequence[str], None] = '1fc756a06ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('learning_records')
    op.drop_table('edu_resource')
    op.drop_table('edu_chat')
    op.drop_index(op.f('username'), table_name='edu_user')
    op.drop_table('edu_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('major', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('username'), 'edu_user', ['username'], unique=True)
    op.create_table('edu_chat',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('session_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('edu_resource',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('resource_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('progress', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('learning_records',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False, comment='记录 id，如 RU0001_000'),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='用户 id，如 U0001'),
    sa.Column('course', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='课程'),
    sa.Column('chapter', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='章节'),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='得分'),
    sa.Column('correct_rate', mysql.DECIMAL(precision=5, scale=4), nullable=True, comment='正确率（0-1）'),
    sa.Column('problems_done', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='完成题目数'),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='持续分钟数'),
    sa.Column('study_date', sa.DATE(), nullable=True, comment='学习日期'),
    sa.Column('time_slot', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='时间段，如 10:00-12:00'),
    sa.Column('raw_json', mysql.JSON(), nullable=True, comment='原始 JSON 数据（可选）'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='姓名'),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='年龄'),
    sa.Column('major', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='专业'),
    sa.Column('course', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='课程'),
    sa.Column('study_goal', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='学习目标'),
    sa.Column('knowledge_level', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='知识基础'),
    sa.Column('learning_preference', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='学习偏好'),
    sa.Column('weak_knowledge', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='薄弱知识'),
    sa.Column('study_time', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='学习时间'),
    sa.Column('raw_json', mysql.JSON(), nullable=True, comment='原始 JSON 数据（可选）'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
